/**
 * Insert random test entries into D1 (notes + photo rows without R2 files).
 *
 * Usage:
 *   node scripts/seed-entries.mjs           # 100 entries, local D1
 *   node scripts/seed-entries.mjs 50      # custom count
 *   node scripts/seed-entries.mjs 100 --remote
 */

import { spawnSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { existsSync, writeFileSync, unlinkSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const backendRoot = join(__dirname, '..');

const NAMES = [
  'Alex', 'Jordan', 'Sam', 'Riley', 'Casey', 'Morgan', 'Quinn', 'Avery',
  'Booty Bear', 'Charles', 'Jamie', 'Taylor', 'Robin', 'Sky', 'Drew',
  'Pat', 'Chris', 'Lee', 'Max', 'River',
];

const NOTE_SNIPPETS = [
  'Happy birthday! Wishing you the best year yet.',
  'Remember that road trip? Still laughing about it.',
  'You make every room brighter.',
  'Here is to more adventures together.',
  'Sending love from far away.',
  'That sunset photo does not do it justice.',
  'Thanks for always showing up.',
  'Inside joke #47: do not forget the snacks.',
  'Proud of you. Always.',
  'Capsule check-in: still grateful for you.',
];

const CAPTIONS = [
  'Throwback moment',
  'Best day ever',
  'Could not resist sharing',
  'Golden hour',
  'Squad goals',
];

function pick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function resolveWranglerBin() {
  const candidates = [
    join(backendRoot, 'node_modules', 'wrangler', 'bin', 'wrangler.js'),
    join(backendRoot, '..', 'node_modules', 'wrangler', 'bin', 'wrangler.js'),
  ];
  for (const p of candidates) {
    if (existsSync(p)) return p;
  }
  throw new Error('wrangler not found — run npm install from the repo root.');
}

function sqlEscape(value) {
  return String(value).replace(/'/g, "''");
}

function buildSeedSql(count) {
  const now = Math.floor(Date.now() / 1000);
  const lines = [
    '-- Generated by scripts/seed-entries.mjs',
    'BEGIN TRANSACTION;',
  ];

  for (let i = 0; i < count; i++) {
    const id = randomUUID();
    const author = pick(NAMES);
    const isPhoto = Math.random() < 0.3;
    const createdAt = now - Math.floor(Math.random() * 365 * 24 * 3600);

    if (isPhoto) {
      const body = pick(CAPTIONS);
      lines.push(
        `INSERT INTO entries (id, type, author_name, body, r2_key, r2_key_thumb, mime_type, created_at)
         VALUES ('${id}', 'photo', '${sqlEscape(author)}', '${sqlEscape(body)}', NULL, NULL, NULL, ${createdAt});`,
      );
    } else {
      const body = pick(NOTE_SNIPPETS);
      lines.push(
        `INSERT INTO entries (id, type, author_name, body, created_at)
         VALUES ('${id}', 'note', '${sqlEscape(author)}', '${sqlEscape(body)}', ${createdAt});`,
      );
    }
  }

  lines.push('COMMIT;');
  return lines.join('\n');
}

function main() {
  const args = process.argv.slice(2).filter((a) => a !== '--remote');
  const remote = process.argv.includes('--remote');
  const count = Math.min(500, Math.max(1, parseInt(args[0] ?? '100', 10) || 100));

  const sql = buildSeedSql(count);
  const sqlPath = join(backendRoot, `.seed-${Date.now()}.sql`);
  writeFileSync(sqlPath, sql, 'utf8');

  const wranglerBin = resolveWranglerBin();
  const wranglerArgs = [
    'd1',
    'execute',
    'birthdaydb',
    remote ? '--remote' : '--local',
    '--file',
    sqlPath,
    '-y',
  ];

  console.log(`Seeding ${count} random entries (${remote ? 'remote' : 'local'} D1)…`);

  const result = spawnSync(process.execPath, [wranglerBin, ...wranglerArgs], {
    cwd: backendRoot,
    stdio: 'inherit',
  });

  try {
    unlinkSync(sqlPath);
  } catch {
    /* ignore */
  }

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }

  console.log(`Done. ${count} test entries added. Refresh the app to see them.`);
}

main();
